services:
  encoder-recorder:
    build: .
    env_file: .env.example
    environment:
      AUTOSTREAM_NODE_CONFIG: /etc/autostream-encoder-recorder/config.yml
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.yml:/etc/autostream-encoder-recorder/config.yml:ro
